/*
	This code was generated by SQL Compact Code Generator version 1.2.1.5

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/19/2011 17:29:26
*/



namespace SmartDeviceApp.TestDatabaseMultiple
{
	/// <summary>
	/// Default IContactRepository implementation 
	/// </summary>
	public partial class ContactRepository : IContactRepository
	{
		public System.Data.SqlServerCe.SqlCeTransaction Transaction { get; set; }

		#region SELECT *

		/// <summary>
		/// Retrieves all items as a generic collection
		/// </summary>
		public System.Collections.Generic.List<Contact> ToList()
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "SELECT * FROM Contact";
				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		public Contact[] ToArray()
		{
			var list = ToList();
			return list != null ? list.ToArray() : null;
		}

		#endregion

		#region SELECT TOP()

		/// <summary>
		/// Retrieves the first set of items specified by count as a generic collection
		/// </summary>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> ToList(int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = string.Format("SELECT TOP({0}) * FROM Contact", count);
				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		public Contact[] ToArray(int count)
		{
			var list = ToList(count);
			return list != null ? list.ToArray() : null;
		}

		#endregion

		#region SELECT .... WHERE Id=?

		/// <summary>
		/// Retrieves a collection of items by Id
		/// </summary>
		/// <param name="Id">Id value</param>
		public System.Collections.Generic.List<Contact> SelectById(System.Int32? Id)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (Id != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE Id=@Id";
					command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
					command.Parameters["@Id"].Value = Id != null ? (object)Id : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE Id IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT .... WHERE Name=?

		/// <summary>
		/// Retrieves a collection of items by Name
		/// </summary>
		/// <param name="Name">Name value</param>
		public System.Collections.Generic.List<Contact> SelectByName(System.String Name)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (Name != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE Name=@Name";
					command.Parameters.Add("@Name", System.Data.SqlDbType.NVarChar);
					command.Parameters["@Name"].Value = Name != null ? (object)Name : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE Name IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT .... WHERE Address=?

		/// <summary>
		/// Retrieves a collection of items by Address
		/// </summary>
		/// <param name="Address">Address value</param>
		public System.Collections.Generic.List<Contact> SelectByAddress(System.String Address)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (Address != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE Address=@Address";
					command.Parameters.Add("@Address", System.Data.SqlDbType.NVarChar);
					command.Parameters["@Address"].Value = Address != null ? (object)Address : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE Address IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT .... WHERE City=?

		/// <summary>
		/// Retrieves a collection of items by City
		/// </summary>
		/// <param name="City">City value</param>
		public System.Collections.Generic.List<Contact> SelectByCity(System.String City)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (City != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE City=@City";
					command.Parameters.Add("@City", System.Data.SqlDbType.NVarChar);
					command.Parameters["@City"].Value = City != null ? (object)City : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE City IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT .... WHERE PostalCode=?

		/// <summary>
		/// Retrieves a collection of items by PostalCode
		/// </summary>
		/// <param name="PostalCode">PostalCode value</param>
		public System.Collections.Generic.List<Contact> SelectByPostalCode(System.String PostalCode)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (PostalCode != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE PostalCode=@PostalCode";
					command.Parameters.Add("@PostalCode", System.Data.SqlDbType.NVarChar);
					command.Parameters["@PostalCode"].Value = PostalCode != null ? (object)PostalCode : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE PostalCode IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT .... WHERE Country=?

		/// <summary>
		/// Retrieves a collection of items by Country
		/// </summary>
		/// <param name="Country">Country value</param>
		public System.Collections.Generic.List<Contact> SelectByCountry(System.String Country)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (Country != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE Country=@Country";
					command.Parameters.Add("@Country", System.Data.SqlDbType.NVarChar);
					command.Parameters["@Country"].Value = Country != null ? (object)Country : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE Country IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT .... WHERE Email=?

		/// <summary>
		/// Retrieves a collection of items by Email
		/// </summary>
		/// <param name="Email">Email value</param>
		public System.Collections.Generic.List<Contact> SelectByEmail(System.String Email)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (Email != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE Email=@Email";
					command.Parameters.Add("@Email", System.Data.SqlDbType.NVarChar);
					command.Parameters["@Email"].Value = Email != null ? (object)Email : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE Email IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT .... WHERE Phone=?

		/// <summary>
		/// Retrieves a collection of items by Phone
		/// </summary>
		/// <param name="Phone">Phone value</param>
		public System.Collections.Generic.List<Contact> SelectByPhone(System.String Phone)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				if (Phone != null)
				{
					command.CommandText = "SELECT * FROM Contact WHERE Phone=@Phone";
					command.Parameters.Add("@Phone", System.Data.SqlDbType.NVarChar);
					command.Parameters["@Phone"].Value = Phone != null ? (object)Phone : System.DBNull.Value;
				}
				else
					command.CommandText = "SELECT * FROM Contact WHERE Phone IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE Id=?

		/// <summary>
		/// Retrieves the first set of items specified by count by Id
		/// </summary>
		/// <param name="Id">Id value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectById(System.Int32? Id, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (Id != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Id=@Id";					command.CommandText = "SELECT * FROM Contact WHERE Id=@Id";
				command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
				command.Parameters["@Id"].Value = Id != null ? (object)Id : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Id IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE Name=?

		/// <summary>
		/// Retrieves the first set of items specified by count by Name
		/// </summary>
		/// <param name="Name">Name value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectByName(System.String Name, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (Name != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Name=@Name";					command.CommandText = "SELECT * FROM Contact WHERE Name=@Name";
				command.Parameters.Add("@Name", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Name"].Value = Name != null ? (object)Name : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Name IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE Address=?

		/// <summary>
		/// Retrieves the first set of items specified by count by Address
		/// </summary>
		/// <param name="Address">Address value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectByAddress(System.String Address, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (Address != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Address=@Address";					command.CommandText = "SELECT * FROM Contact WHERE Address=@Address";
				command.Parameters.Add("@Address", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Address"].Value = Address != null ? (object)Address : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Address IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE City=?

		/// <summary>
		/// Retrieves the first set of items specified by count by City
		/// </summary>
		/// <param name="City">City value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectByCity(System.String City, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (City != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE City=@City";					command.CommandText = "SELECT * FROM Contact WHERE City=@City";
				command.Parameters.Add("@City", System.Data.SqlDbType.NVarChar);
				command.Parameters["@City"].Value = City != null ? (object)City : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE City IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE PostalCode=?

		/// <summary>
		/// Retrieves the first set of items specified by count by PostalCode
		/// </summary>
		/// <param name="PostalCode">PostalCode value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectByPostalCode(System.String PostalCode, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (PostalCode != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE PostalCode=@PostalCode";					command.CommandText = "SELECT * FROM Contact WHERE PostalCode=@PostalCode";
				command.Parameters.Add("@PostalCode", System.Data.SqlDbType.NVarChar);
				command.Parameters["@PostalCode"].Value = PostalCode != null ? (object)PostalCode : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE PostalCode IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE Country=?

		/// <summary>
		/// Retrieves the first set of items specified by count by Country
		/// </summary>
		/// <param name="Country">Country value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectByCountry(System.String Country, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (Country != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Country=@Country";					command.CommandText = "SELECT * FROM Contact WHERE Country=@Country";
				command.Parameters.Add("@Country", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Country"].Value = Country != null ? (object)Country : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Country IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE Email=?

		/// <summary>
		/// Retrieves the first set of items specified by count by Email
		/// </summary>
		/// <param name="Email">Email value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectByEmail(System.String Email, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (Email != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Email=@Email";					command.CommandText = "SELECT * FROM Contact WHERE Email=@Email";
				command.Parameters.Add("@Email", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Email"].Value = Email != null ? (object)Email : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Email IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region SELECT TOP(?).... WHERE Phone=?

		/// <summary>
		/// Retrieves the first set of items specified by count by Phone
		/// </summary>
		/// <param name="Phone">Phone value</param>
		/// <param name="count">Number of records to be retrieved</param>
		public System.Collections.Generic.List<Contact> SelectByPhone(System.String Phone, int count)
		{
			var list = new System.Collections.Generic.List<Contact>();
			using (var command = EntityBase.CreateCommand(Transaction))
			{
			if (Phone != null)
			{
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Phone=@Phone";					command.CommandText = "SELECT * FROM Contact WHERE Phone=@Phone";
				command.Parameters.Add("@Phone", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Phone"].Value = Phone != null ? (object)Phone : System.DBNull.Value;
			}
			else
				command.CommandText = "SELECT TOP(" + count + ") * FROM Contact WHERE Phone IS NULL";

				using (var reader = command.ExecuteReader())
				{
					while (reader.Read())
					{
						var item = new Contact();
						item.Id = (System.Int32?) (reader.IsDBNull(0) ? null : reader["Id"]);
						item.Name = (reader.IsDBNull(1) ? null : reader["Name"] as System.String);
						item.Address = (reader.IsDBNull(2) ? null : reader["Address"] as System.String);
						item.City = (reader.IsDBNull(3) ? null : reader["City"] as System.String);
						item.PostalCode = (reader.IsDBNull(4) ? null : reader["PostalCode"] as System.String);
						item.Country = (reader.IsDBNull(5) ? null : reader["Country"] as System.String);
						item.Email = (reader.IsDBNull(6) ? null : reader["Email"] as System.String);
						item.Phone = (reader.IsDBNull(7) ? null : reader["Phone"] as System.String);
						list.Add(item);
					}
				}
			}
			return list.Count > 0 ? list : null;
		}

		#endregion

		#region INSERT [Contact]

		/// <summary>
		/// Inserts the item to the table
		/// </summary>
		/// <param name="item">Item to insert to the database</param>
		public void Create(Contact item)
		{
			Create(item.Name, item.Address, item.City, item.PostalCode, item.Country, item.Email, item.Phone);
		}

		#endregion

		#region INSERT Ignoring Primary Key

		/// <summary>
		/// Inserts a new record to the table without specifying the primary key
		/// </summary>
		/// <param name="Name">Name value</param>
		/// <param name="Address">Address value</param>
		/// <param name="City">City value</param>
		/// <param name="PostalCode">PostalCode value</param>
		/// <param name="Country">Country value</param>
		/// <param name="Email">Email value</param>
		/// <param name="Phone">Phone value</param>
		public void Create(System.String Name, System.String Address, System.String City, System.String PostalCode, System.String Country, System.String Email, System.String Phone)
		{
			if (Name != null && Name.Length > 100)
				throw new System.ArgumentException("Max length for Name is 100");
			if (Address != null && Address.Length > 100)
				throw new System.ArgumentException("Max length for Address is 100");
			if (City != null && City.Length > 100)
				throw new System.ArgumentException("Max length for City is 100");
			if (PostalCode != null && PostalCode.Length > 100)
				throw new System.ArgumentException("Max length for PostalCode is 100");
			if (Country != null && Country.Length > 100)
				throw new System.ArgumentException("Max length for Country is 100");
			if (Email != null && Email.Length > 100)
				throw new System.ArgumentException("Max length for Email is 100");
			if (Phone != null && Phone.Length > 100)
				throw new System.ArgumentException("Max length for Phone is 100");

			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "INSERT INTO [Contact] (Name, Address, City, PostalCode, Country, Email, Phone)  VALUES (@Name, @Address, @City, @PostalCode, @Country, @Email, @Phone)";

				command.Parameters.Add("@Name", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Name"].Value = Name != null ? (object)Name : System.DBNull.Value;
				command.Parameters.Add("@Address", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Address"].Value = Address != null ? (object)Address : System.DBNull.Value;
				command.Parameters.Add("@City", System.Data.SqlDbType.NVarChar);
				command.Parameters["@City"].Value = City != null ? (object)City : System.DBNull.Value;
				command.Parameters.Add("@PostalCode", System.Data.SqlDbType.NVarChar);
				command.Parameters["@PostalCode"].Value = PostalCode != null ? (object)PostalCode : System.DBNull.Value;
				command.Parameters.Add("@Country", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Country"].Value = Country != null ? (object)Country : System.DBNull.Value;
				command.Parameters.Add("@Email", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Email"].Value = Email != null ? (object)Email : System.DBNull.Value;
				command.Parameters.Add("@Phone", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Phone"].Value = Phone != null ? (object)Phone : System.DBNull.Value;
				command.ExecuteNonQuery();
			}
		}

		#endregion

		#region INSERT [Contact] by fields

		/// <summary>
		/// Inserts a new record to the table specifying all fields
		/// </summary>
		/// <param name="Id">Id value</param>
		/// <param name="Name">Name value</param>
		/// <param name="Address">Address value</param>
		/// <param name="City">City value</param>
		/// <param name="PostalCode">PostalCode value</param>
		/// <param name="Country">Country value</param>
		/// <param name="Email">Email value</param>
		/// <param name="Phone">Phone value</param>
		public void Create(System.Int32? Id, System.String Name, System.String Address, System.String City, System.String PostalCode, System.String Country, System.String Email, System.String Phone)
		{
			if (Name != null && Name.Length > Contact.Name_Max_Length)
				throw new System.ArgumentException("Max length for Name is 100");
			if (Address != null && Address.Length > Contact.Address_Max_Length)
				throw new System.ArgumentException("Max length for Address is 100");
			if (City != null && City.Length > Contact.City_Max_Length)
				throw new System.ArgumentException("Max length for City is 100");
			if (PostalCode != null && PostalCode.Length > Contact.PostalCode_Max_Length)
				throw new System.ArgumentException("Max length for PostalCode is 100");
			if (Country != null && Country.Length > Contact.Country_Max_Length)
				throw new System.ArgumentException("Max length for Country is 100");
			if (Email != null && Email.Length > Contact.Email_Max_Length)
				throw new System.ArgumentException("Max length for Email is 100");
			if (Phone != null && Phone.Length > Contact.Phone_Max_Length)
				throw new System.ArgumentException("Max length for Phone is 100");

			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "INSERT INTO [Contact] (Id, Name, Address, City, PostalCode, Country, Email, Phone)  VALUES (@Id, @Name, @Address, @City, @PostalCode, @Country, @Email, @Phone)";

				command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
				command.Parameters["@Id"].Value = Id != null ? (object)Id : System.DBNull.Value;
				command.Parameters.Add("@Name", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Name"].Value = Name != null ? (object)Name : System.DBNull.Value;
				command.Parameters.Add("@Address", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Address"].Value = Address != null ? (object)Address : System.DBNull.Value;
				command.Parameters.Add("@City", System.Data.SqlDbType.NVarChar);
				command.Parameters["@City"].Value = City != null ? (object)City : System.DBNull.Value;
				command.Parameters.Add("@PostalCode", System.Data.SqlDbType.NVarChar);
				command.Parameters["@PostalCode"].Value = PostalCode != null ? (object)PostalCode : System.DBNull.Value;
				command.Parameters.Add("@Country", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Country"].Value = Country != null ? (object)Country : System.DBNull.Value;
				command.Parameters.Add("@Email", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Email"].Value = Email != null ? (object)Email : System.DBNull.Value;
				command.Parameters.Add("@Phone", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Phone"].Value = Phone != null ? (object)Phone : System.DBNull.Value;
				command.ExecuteNonQuery();
			}
		}

		#endregion

		#region INSERT MANY

		/// <summary>
		/// Populates the table with a collection of items
		/// </summary>
		public void Create(System.Collections.Generic.IEnumerable<Contact> items)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandType = System.Data.CommandType.TableDirect;
				command.CommandText = "Contact";

				using (var resultSet = command.ExecuteResultSet(System.Data.SqlServerCe.ResultSetOptions.Updatable))
				{
					var record = resultSet.CreateRecord();
					foreach (var item in items)
					{
						record.SetValue(1, item.Name);
						record.SetValue(2, item.Address);
						record.SetValue(3, item.City);
						record.SetValue(4, item.PostalCode);
						record.SetValue(5, item.Country);
						record.SetValue(6, item.Email);
						record.SetValue(7, item.Phone);
						resultSet.Insert(record);
					}
				}
			}
		}

		#endregion

		#region DELETE

		/// <summary>
		/// Deletes the item
		/// </summary>
		/// <param name="item">Item to delete</param>
		public void Delete(Contact item)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Id = @Id";

				command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
				command.Parameters["@Id"].Value = item.Id != null ? (object)item.Id : System.DBNull.Value;
				command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE MANY

		/// <summary>
		/// Deletes a collection of item
		/// </summary>
		/// <param name="items">Items to delete</param>
		public void Delete(System.Collections.Generic.IEnumerable<Contact> items)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Id = @Id";
				command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
				command.Prepare();

				foreach (var item in items)
				{
					command.Parameters["@Id"].Value = item.Id != null ? (object)item.Id : System.DBNull.Value;

					command.ExecuteNonQuery();
				}
			}
		}

		#endregion

		#region DELETE BY Id

		/// <summary>
		/// Delete records by Id
		/// </summary>
		/// <param name="Id">Id value</param>
		public int DeleteById(System.Int32? Id)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Id=@Id";
				command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
				command.Parameters["@Id"].Value = Id != null ? (object)Id : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE BY Name

		/// <summary>
		/// Delete records by Name
		/// </summary>
		/// <param name="Name">Name value</param>
		public int DeleteByName(System.String Name)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Name=@Name";
				command.Parameters.Add("@Name", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Name"].Value = Name != null ? (object)Name : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE BY Address

		/// <summary>
		/// Delete records by Address
		/// </summary>
		/// <param name="Address">Address value</param>
		public int DeleteByAddress(System.String Address)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Address=@Address";
				command.Parameters.Add("@Address", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Address"].Value = Address != null ? (object)Address : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE BY City

		/// <summary>
		/// Delete records by City
		/// </summary>
		/// <param name="City">City value</param>
		public int DeleteByCity(System.String City)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE City=@City";
				command.Parameters.Add("@City", System.Data.SqlDbType.NVarChar);
				command.Parameters["@City"].Value = City != null ? (object)City : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE BY PostalCode

		/// <summary>
		/// Delete records by PostalCode
		/// </summary>
		/// <param name="PostalCode">PostalCode value</param>
		public int DeleteByPostalCode(System.String PostalCode)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE PostalCode=@PostalCode";
				command.Parameters.Add("@PostalCode", System.Data.SqlDbType.NVarChar);
				command.Parameters["@PostalCode"].Value = PostalCode != null ? (object)PostalCode : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE BY Country

		/// <summary>
		/// Delete records by Country
		/// </summary>
		/// <param name="Country">Country value</param>
		public int DeleteByCountry(System.String Country)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Country=@Country";
				command.Parameters.Add("@Country", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Country"].Value = Country != null ? (object)Country : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE BY Email

		/// <summary>
		/// Delete records by Email
		/// </summary>
		/// <param name="Email">Email value</param>
		public int DeleteByEmail(System.String Email)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Email=@Email";
				command.Parameters.Add("@Email", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Email"].Value = Email != null ? (object)Email : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region DELETE BY Phone

		/// <summary>
		/// Delete records by Phone
		/// </summary>
		/// <param name="Phone">Phone value</param>
		public int DeleteByPhone(System.String Phone)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact] WHERE Phone=@Phone";
				command.Parameters.Add("@Phone", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Phone"].Value = Phone != null ? (object)Phone : System.DBNull.Value;

				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region Purge

		/// <summary>
		/// Purges the contents of the table
		/// </summary>
		public int Purge()
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "DELETE FROM [Contact]";
				return command.ExecuteNonQuery();
			}
		}

		#endregion

		#region UPDATE

		/// <summary>
		/// Updates the item
		/// </summary>
		/// <param name="item">Item to update</param>
		public void Update(Contact item)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "UPDATE [Contact] SET Name = @Name, Address = @Address, City = @City, PostalCode = @PostalCode, Country = @Country, Email = @Email, Phone = @Phone WHERE Id = @Id";

				command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
				command.Parameters["@Id"].Value = item.Id != null ? (object)item.Id : System.DBNull.Value;
				command.Parameters.Add("@Name", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Name"].Value = item.Name != null ? (object)item.Name : System.DBNull.Value;
				command.Parameters.Add("@Address", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Address"].Value = item.Address != null ? (object)item.Address : System.DBNull.Value;
				command.Parameters.Add("@City", System.Data.SqlDbType.NVarChar);
				command.Parameters["@City"].Value = item.City != null ? (object)item.City : System.DBNull.Value;
				command.Parameters.Add("@PostalCode", System.Data.SqlDbType.NVarChar);
				command.Parameters["@PostalCode"].Value = item.PostalCode != null ? (object)item.PostalCode : System.DBNull.Value;
				command.Parameters.Add("@Country", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Country"].Value = item.Country != null ? (object)item.Country : System.DBNull.Value;
				command.Parameters.Add("@Email", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Email"].Value = item.Email != null ? (object)item.Email : System.DBNull.Value;
				command.Parameters.Add("@Phone", System.Data.SqlDbType.NVarChar);
				command.Parameters["@Phone"].Value = item.Phone != null ? (object)item.Phone : System.DBNull.Value;
				command.ExecuteNonQuery();
			}
		}

		#endregion

		#region UPDATE MANY

		/// <summary>
		/// Updates a collection of items
		/// </summary>
		/// <param name="items">Items to update</param>
		public void Update(System.Collections.Generic.IEnumerable<Contact> items)
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "UPDATE [Contact] SET Name = @Name, Address = @Address, City = @City, PostalCode = @PostalCode, Country = @Country, Email = @Email, Phone = @Phone WHERE Id = @Id";
				command.Parameters.Add("@Id", System.Data.SqlDbType.Int);
				command.Parameters.Add("@Name", System.Data.SqlDbType.NVarChar);
				command.Parameters.Add("@Address", System.Data.SqlDbType.NVarChar);
				command.Parameters.Add("@City", System.Data.SqlDbType.NVarChar);
				command.Parameters.Add("@PostalCode", System.Data.SqlDbType.NVarChar);
				command.Parameters.Add("@Country", System.Data.SqlDbType.NVarChar);
				command.Parameters.Add("@Email", System.Data.SqlDbType.NVarChar);
				command.Parameters.Add("@Phone", System.Data.SqlDbType.NVarChar);
				command.Prepare();

				foreach (var item in items)
				{
					command.Parameters["@Id"].Value = item.Id != null ? (object)item.Id : System.DBNull.Value;
					command.Parameters["@Name"].Value = item.Name != null ? (object)item.Name : System.DBNull.Value;
					command.Parameters["@Address"].Value = item.Address != null ? (object)item.Address : System.DBNull.Value;
					command.Parameters["@City"].Value = item.City != null ? (object)item.City : System.DBNull.Value;
					command.Parameters["@PostalCode"].Value = item.PostalCode != null ? (object)item.PostalCode : System.DBNull.Value;
					command.Parameters["@Country"].Value = item.Country != null ? (object)item.Country : System.DBNull.Value;
					command.Parameters["@Email"].Value = item.Email != null ? (object)item.Email : System.DBNull.Value;
					command.Parameters["@Phone"].Value = item.Phone != null ? (object)item.Phone : System.DBNull.Value;
					command.ExecuteNonQuery();
				}
			}
		}

		#endregion

		#region COUNT [Contact]

		/// <summary>
		/// Gets the number of records in the table
		/// </summary>
		public int Count()
		{
			using (var command = EntityBase.CreateCommand(Transaction))
			{
				command.CommandText = "SELECT COUNT(*) FROM Contact";
				return (int)command.ExecuteScalar();
			}
		}

		#endregion

	}
}

