/*
	This code was generated by SQL Compact Code Generator version 1.2.1.5

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/19/2011 17:29:26
*/



namespace SmartDeviceApp.TestDatabaseMultiple
{
	/// <summary>
	/// Represents the Contact table
	/// </summary>
	public partial class Contact
	{
		private System.Int32? _Id;
		/// <summary>
		/// Gets or sets the value of Id
		/// </summary>
		public System.Int32? Id
		{
			get { return _Id; }
			set
			{
				_Id = value;
			}
		}
		private System.String _Name;
		/// <summary>
		/// The Maximum Length the Name field allows
		/// </summary>
		public const int Name_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Name
		/// </summary>
		public System.String Name
		{
			get { return _Name; }
			set
			{
				_Name = value;
				if (_Name != null && Name.Length > Name_Max_Length)
					throw new System.ArgumentException("Max length for Name is 100");
			}
		}
		private System.String _Address;
		/// <summary>
		/// The Maximum Length the Address field allows
		/// </summary>
		public const int Address_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Address
		/// </summary>
		public System.String Address
		{
			get { return _Address; }
			set
			{
				_Address = value;
				if (_Address != null && Address.Length > Address_Max_Length)
					throw new System.ArgumentException("Max length for Address is 100");
			}
		}
		private System.String _City;
		/// <summary>
		/// The Maximum Length the City field allows
		/// </summary>
		public const int City_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of City
		/// </summary>
		public System.String City
		{
			get { return _City; }
			set
			{
				_City = value;
				if (_City != null && City.Length > City_Max_Length)
					throw new System.ArgumentException("Max length for City is 100");
			}
		}
		private System.String _PostalCode;
		/// <summary>
		/// The Maximum Length the PostalCode field allows
		/// </summary>
		public const int PostalCode_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of PostalCode
		/// </summary>
		public System.String PostalCode
		{
			get { return _PostalCode; }
			set
			{
				_PostalCode = value;
				if (_PostalCode != null && PostalCode.Length > PostalCode_Max_Length)
					throw new System.ArgumentException("Max length for PostalCode is 100");
			}
		}
		private System.String _Country;
		/// <summary>
		/// The Maximum Length the Country field allows
		/// </summary>
		public const int Country_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Country
		/// </summary>
		public System.String Country
		{
			get { return _Country; }
			set
			{
				_Country = value;
				if (_Country != null && Country.Length > Country_Max_Length)
					throw new System.ArgumentException("Max length for Country is 100");
			}
		}
		private System.String _Email;
		/// <summary>
		/// The Maximum Length the Email field allows
		/// </summary>
		public const int Email_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Email
		/// </summary>
		public System.String Email
		{
			get { return _Email; }
			set
			{
				_Email = value;
				if (_Email != null && Email.Length > Email_Max_Length)
					throw new System.ArgumentException("Max length for Email is 100");
			}
		}
		private System.String _Phone;
		/// <summary>
		/// The Maximum Length the Phone field allows
		/// </summary>
		public const int Phone_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Phone
		/// </summary>
		public System.String Phone
		{
			get { return _Phone; }
			set
			{
				_Phone = value;
				if (_Phone != null && Phone.Length > Phone_Max_Length)
					throw new System.ArgumentException("Max length for Phone is 100");
			}
		}
	}
}

