/*
	This code was generated by SQL Compact Code Generator version 1.2.1.5

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/19/2011 18:06:46
*/



namespace ConsoleApp.TestDatabaseMultiple
{
	/// <summary>
	/// Helper class for generating the database file in runtime
	/// </summary>
	public static class DatabaseFile
	{
		/// <summary>
		/// Creates the database
		/// </summary>
		public static int CreateDatabase()
		{
			int resultCount = 0;

			using (var engine = new System.Data.SqlServerCe.SqlCeEngine(EntityBase.ConnectionString))
				engine.CreateDatabase();

			using (var transaction = EntityBase.Connection.BeginTransaction())
			using (var command = EntityBase.CreateCommand(transaction))
			{
				command.CommandText = "CREATE TABLE [Contact](Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL, Name NVARCHAR(100), Address NVARCHAR(100), City NVARCHAR(100), PostalCode NVARCHAR(100), Country NVARCHAR(100), Email NVARCHAR(100), Phone NVARCHAR(100))";
				resultCount += command.ExecuteNonQuery();

				command.CommandText = "CREATE TABLE [Customer](Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL, ContactId INT, Name NVARCHAR(100), Address NVARCHAR(100), City NVARCHAR(100), PostalCode NVARCHAR(100), Country NVARCHAR(100), Email NVARCHAR(100), Phone NVARCHAR(100), Fax NVARCHAR(100))";
				resultCount += command.ExecuteNonQuery();

				command.CommandText = "CREATE TABLE [Product](Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL, PartNumber NVARCHAR(100), Ean13 NVARCHAR(100), Name NVARCHAR(100), Description NVARCHAR(100), Rating NUMERIC)";
				resultCount += command.ExecuteNonQuery();

				command.CommandText = "CREATE TABLE [Stock](Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL, ProductId INT, Quantity INT, LastUpdated DATETIME)";
				resultCount += command.ExecuteNonQuery();
				transaction.Commit();
			}

			return resultCount;
		}
	}
}

