/*
	This code was generated by SQL Compact Code Generator version 1.2.1.5

	SQL Compact Code Generator was written by Christian Resma Helle (http://sqlcecodegen.codeplex.com)
	and is under the GNU General Public License version 2 (GPLv2)

	Generated: 07/19/2011 18:06:46
*/



namespace ConsoleApp.TestDatabaseMultiple
{
	/// <summary>
	/// Represents the Product table
	/// </summary>
	public partial class Product
	{
		private System.Int32? _Id;
		/// <summary>
		/// Gets or sets the value of Id
		/// </summary>
		public System.Int32? Id
		{
			get { return _Id; }
			set
			{
				_Id = value;
			}
		}
		private System.String _PartNumber;
		/// <summary>
		/// The Maximum Length the PartNumber field allows
		/// </summary>
		public const int PartNumber_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of PartNumber
		/// </summary>
		public System.String PartNumber
		{
			get { return _PartNumber; }
			set
			{
				_PartNumber = value;
				if (_PartNumber != null && PartNumber.Length > PartNumber_Max_Length)
					throw new System.ArgumentException("Max length for PartNumber is 100");
			}
		}
		private System.String _Ean13;
		/// <summary>
		/// The Maximum Length the Ean13 field allows
		/// </summary>
		public const int Ean13_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Ean13
		/// </summary>
		public System.String Ean13
		{
			get { return _Ean13; }
			set
			{
				_Ean13 = value;
				if (_Ean13 != null && Ean13.Length > Ean13_Max_Length)
					throw new System.ArgumentException("Max length for Ean13 is 100");
			}
		}
		private System.String _Name;
		/// <summary>
		/// The Maximum Length the Name field allows
		/// </summary>
		public const int Name_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Name
		/// </summary>
		public System.String Name
		{
			get { return _Name; }
			set
			{
				_Name = value;
				if (_Name != null && Name.Length > Name_Max_Length)
					throw new System.ArgumentException("Max length for Name is 100");
			}
		}
		private System.String _Description;
		/// <summary>
		/// The Maximum Length the Description field allows
		/// </summary>
		public const int Description_Max_Length = 100;
		/// <summary>
		/// Gets or sets the value of Description
		/// </summary>
		public System.String Description
		{
			get { return _Description; }
			set
			{
				_Description = value;
				if (_Description != null && Description.Length > Description_Max_Length)
					throw new System.ArgumentException("Max length for Description is 100");
			}
		}
		private System.Decimal? _Rating;
		/// <summary>
		/// Gets or sets the value of Rating
		/// </summary>
		public System.Decimal? Rating
		{
			get { return _Rating; }
			set
			{
				_Rating = value;
			}
		}
	}
}

